# HITO-Toolset, Maintainer: Konrad Höffner <konrad.hoeffner@imise.uni-leipzig.de>, originally Sebastian Stäubert  <sebastian.staeubert@imise.uni-leipzig.de>

services:

  # Access at http://localhost:8102/sparql
  virtuoso:
    image: pkleef/virtuoso-opensource-7
    environment:
      - DBA_PASSWORD=${DBA_PASSWORD}
      - VIRT_DATABASE_ERRORLOGLEVEL=3
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=${VIRT_PARAMETERS_NUMBEROFBUFFERS}
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=${VIRT_PARAMETERS_MAXDIRTYBUFFERS}
      - VIRT_HTTPSERVER_SERVERPORT=8890
      - VIRT_SPARQL_DEFAULTGRAPH=http://hitontology.eu/ontology
      - VIRT_SPARQL_RESULTSETMAXROWS=50000
      - VIRT_SPARQL_MAXQUERYCOSTESTIMATIONTIME=400
      - VIRT_SPARQL_MAXQUERYEXECUTIONTIME=120
      - VIRT_SPARQL_DEFAULTQUERY=select distinct * {?s a hito:SoftwareProduct.} LIMIT 100
      - VIRT_PARAMETERS_DIRSALLOWED=., /usr/local/virtuoso-opensource/share/virtuoso/vad
      - VIRT_HTTPSERVER_ENABLEDGZIPCONTENT=1
      - VIRT_PLUGINS_-=-
    volumes:
      # Virtuoso loads each ttl file from the local ontology directory root including SHACL shapes into the HITO graph.
      - ./ontology:/database/data
      - ./virtuoso:/opt/virtuoso-opensource/initdb.d:ro
    ports:
      - "127.0.0.1:8102:8890"
      - "127.0.0.1:8103:1111"
    restart: unless-stopped

  # Access at http://localhost:8104/ontology
  rickview:
    image: ghcr.io/konradhoeffner/rickview:master
    environment:
      - RICKVIEW_KB_FILE=/ontology/
      - RICKVIEW_BASE=/ontology
      - RICKVIEW_TITLE=HITO
      - RICKVIEW_SUBTITLE=Health IT Ontology
      - RICKVIEW_PREFIX=hito
      - RICKVIEW_NAMESPACE=http://hitontology.eu/ontology/
      - RICKVIEW_EXAMPLES=Study SoftwareProduct ApplicationSystemTypeCatalogue
      - RICKVIEW_HOMEPAGE=https://hitontology.eu
      - RICKVIEW_ENDPOINT=https://hitontology.eu/sparql
      - RICKVIEW_GITHUB=https://github.com/hitontology/ontology
      - RICKVIEW_DOC=https://hitontology.github.io/ontology/
    ports:
      - "127.0.0.1:8104:8080"
    restart: unless-stopped
    volumes:
      - ./ontology:/ontology/

  # activate the proxy profile for local development so you don't have to type in port numbers:
  # http://localhost/sparql
  # http://localhost/ontology
  proxy:
    image: caddy:2-alpine
    profiles: ["proxy"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "127.0.0.1:80:80"
