# HITO-Toolset, Maintainer: Konrad Höffner <konrad.hoeffner@imise.uni-leipzig.de>, originally Sebastian Stäubert  <sebastian.staeubert@imise.uni-leipzig.de>

services:

  rdf:
    build: ../ontology
    volumes:
      - rdf:/ontology/dist

  virtuoso:
    build: ./virtuoso
    environment:
      - DBA_PASSWORD=${DBA_PASSWORD}
      - SPARQL_UPDATE='false'
      #- DEFAULT_GRAPH=http://hitontology.snik.eu/ontology
    volumes:
      - virtuoso-data:/data
      - rdf:/data/toLoad:ro
    ports:
      - "127.0.0.1:8102:8890"
      - "127.0.0.1:8103:1111"
    restart: unless-stopped
    depends_on:
      rdf: 
        condition: service_completed_successfully

# Access at http://localhost:8104/ontology
  lodview:
    # subfolder, uses the master branch of https://github.com/hitontology/lodview
    # ignore the Dockerfile in the lodview Git repository, it is not used here and may have different settings
    build:
      context: ./lodview
      args:
      # server side, so we use the port on the internal port
        - SPARQL_ENDPOINT=http://virtuoso:8890/sparql
    ports:
      - "127.0.0.1:8104:8080"
    depends_on: 
      - virtuoso
    restart: unless-stopped

  sparqltosql:
    build: ../database
    volumes:
      - rdf:/rdf
      - sql:/sql
    depends_on:
      rdf: 
        condition: service_completed_successfully
    command: ["python", "download.py"]

  postgresql:
    # upgrade to postgresql 14 when available for Arch Linux for local testing
    image: postgres:13
    restart: unless-stopped
    ports:
      - "127.0.0.1:55432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - sql:/docker-entrypoint-initdb.d
    depends_on:
      sparqltosql:
        condition: service_completed_successfully

  phppgadmin:
    #restart: unless-stopped
    #image: dockage/phppgadmin:latest
    image: bitnami/phppgadmin:latest
    ports:
      - "127.0.0.1:8111:8080"
      #- "443:443"
      #- '80:8080'
    depends_on:
      - postgresql
  
  database-frontend:
    restart: unless-stopped
    build: ../database-frontend
    depends_on:
      - postgresql
    ports:
      - "127.0.0.1:8112:5000"
    environment:
      - HITO_DATABASE_HOST=postgresql
      - HITO_DATABASE_PORT=5432
      - HITO_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - HITO_DATABASE_NAME=postgres
      - HITO_DATABASE_FRONTEND_REVERSE_PROXY_PATH=/database-frontend
      #- HITO_DATABASE_FRONTEND_SERVER_NAME=bruchtal.imise.uni-leipzig.de/database-frontend

volumes:
  rdf:
  virtuoso-data:
  postgres-data:
  sql:
