# syntax=docker/dockerfile:1
FROM alpine as builder
RUN apk add raptor2
WORKDIR /build
COPY --from=ontology ./scripts/combine ./scripts/
COPY --from=ontology ./*.ttl ./
RUN ./scripts/combine

FROM ghcr.io/konradhoeffner/rickview:master
COPY --link --from=builder /build/dist/hito.ttl /rdf/hito.ttl
